[package]
name = "simplecrypt"
description = "simple wrapper around sodiumoxide (libsodium) to easily encrypt and decrypt data with a secret key"
version = "0.1.0"
authors = ["Jonas <me@jbrn.eu>"]
edition = "2018"

[dependencies]
sodiumoxide = "0.2.5"
thiserror = "1.0.16"